# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorysettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useditem",
            name="timestamp_returned",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
