# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_auto_20161114_0957"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Comment"),
        ),
    ]
