# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_auto_20170330_2242"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["barcode"]},
        ),
    ]
