# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
