# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254, verbose_name='Name')),
                ('gifts', models.ManyToManyField(to='gifts.Gift', verbose_name='Gifts')),
            ],
        ),
    ]
