# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20160514_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='giftset',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='giftset',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='giftset',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
