# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160415_2121'),
        ('gifts', '0002_giftset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeservedGiftSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False, verbose_name='Helper got gift')),
                ('gift_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.GiftSet')),
            ],
        ),
        migrations.CreateModel(
            name='HelpersGifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Deposit')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='Deposit returned')),
                ('deserved_gifts', models.ManyToManyField(blank=True, through='gifts.DeservedGiftSet', to='gifts.GiftSet', verbose_name='Deserved gifts')),
                ('helper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='registration.Helper')),
            ],
        ),
        migrations.AddField(
            model_name='deservedgiftset',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.HelpersGifts'),
        ),
        migrations.AddField(
            model_name='deservedgiftset',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Shift'),
        ),
    ]
