# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0013_auto_20160704_1214"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentMail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender", models.EmailField(max_length=254)),
                ("cc", models.EmailField(max_length=254)),
                ("response_to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("all_helpers_and_coordinators", models.BooleanField(default=False)),
                ("all_coordinators", models.BooleanField(default=False)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registration.Event")),
                ("jobs_all", models.ManyToManyField(blank=True, related_name="sent_mails_all", to="registration.Job")),
                (
                    "jobs_only_coordinators",
                    models.ManyToManyField(
                        blank=True, related_name="sent_mails_only_coordinators", to="registration.Job"
                    ),
                ),
                ("shifts", models.ManyToManyField(blank=True, to="registration.Shift")),
            ],
        ),
    ]
