# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_auto_20160730_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentmail",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registration.Event"),
        ),
    ]
