# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0005_sentmail_failed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentmail",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="sentmail",
            old_name="response_to",
            new_name="reply_to",
        ),
    ]
