# Generated by Django 2.2.1 on 2019-06-17 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0030_helper_mail_failed"),
        ("mail", "0006_auto_20160730_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentmail",
            name="tracking_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MailDelivery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("failed", models.CharField(blank=True, default=None, max_length=512, null=True)),
                ("helper", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registration.Helper")),
                ("sentmail", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mail.SentMail")),
            ],
        ),
        migrations.AddField(
            model_name="sentmail",
            name="tracking_helper",
            field=models.ManyToManyField(through="mail.MailDelivery", to="registration.Helper"),
        ),
    ]
