# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreement",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="useragreement",
            name="first_displayed",
        ),
    ]
