# Generated by Django 5.2.9 on 2026-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_auto_20210523_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="text_de",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="text_en",
            field=models.TextField(null=True),
        ),
    ]
