# Generated by Django 5.2.9 on 2026-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_agreement_text_alter_agreement_text_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="text",
            field=models.TextField(verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="text_de",
            field=models.TextField(null=True, verbose_name="Text"),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Text"),
        ),
    ]
