# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_tokens_remove_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="id",
        ),
        migrations.AlterField(
            model_name="person",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
