# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_auto_20170326_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="withevent",
            field=models.BooleanField(default=True, verbose_name="Helper subscribed during registration for event"),
        ),
    ]
