# Generated by Django 2.2 on 2019-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_person_withevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["timestamp"]},
        ),
    ]
