# Generated by Django 3.2.6 on 2021-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_auto_20190428_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="timestamp_validated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="validated",
            field=models.BooleanField(default=True, verbose_name="Validation e-mail was confirmed (double opt-in)"),
        ),
    ]
