# Generated by Django 3.2.7 on 2021-09-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0055_event_corona"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoronaSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registration.event")),
            ],
        ),
    ]
