# Generated by Django 4.2.21 on 2025-12-22 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registration", "0065_alter_event_shirt_sizes_alter_helper_shirt"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventArchiveAutomation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reminder_first", models.DateTimeField(blank=True, null=True)),
                ("reminder_latest", models.DateTimeField(blank=True, null=True)),
                ("exception_date", models.DateField(blank=True, null=True)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registration.event")),
            ],
        ),
    ]
