# Generated by Django 4.2.21 on 2025-12-22 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminautomation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventarchiveautomation",
            old_name="reminder_first",
            new_name="last_reminder",
        ),
        migrations.RemoveField(
            model_name="eventarchiveautomation",
            name="reminder_latest",
        ),
    ]
