# Generated by Django 4.2.21 on 2025-12-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminautomation", "0002_rename_reminder_first_eventarchiveautomation_last_reminder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventarchiveautomation",
            name="last_reminder",
            field=models.DateField(blank=True, null=True),
        ),
    ]
