# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):
    replaces = [
        ("toolsettings", "0001_initial"),
        ("toolsettings", "0002_auto_20180624_1505"),
        ("toolsettings", "0003_auto_20180708_1917"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HTMLSetting",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9]+$")],
                        verbose_name="Key",
                    ),
                ),
                ("value", django_bleach.models.BleachField(blank=True, default="", verbose_name="HTML")),
                ("value_de", django_bleach.models.BleachField(blank=True, default="", null=True, verbose_name="HTML")),
                ("value_en", django_bleach.models.BleachField(blank=True, default="", null=True, verbose_name="HTML")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TextSetting",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9]+$")],
                        verbose_name="Key",
                    ),
                ),
                ("value", models.TextField(blank=True, default="", verbose_name="Text")),
                ("value_de", models.TextField(blank=True, default="", null=True, verbose_name="Text")),
                ("value_en", models.TextField(blank=True, default="", null=True, verbose_name="Text")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
