# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')], verbose_name='Key')),
                ('value', django_bleach.models.BleachField(blank=True, verbose_name='HTML')),
                ('value_de', django_bleach.models.BleachField(blank=True, null=True, verbose_name='HTML')),
                ('value_en', django_bleach.models.BleachField(blank=True, null=True, verbose_name='HTML')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')], verbose_name='Key')),
                ('value', models.TextField(blank=True, verbose_name='Text')),
                ('value_de', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('value_en', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
