# Generated by Django 5.2.9 on 2026-01-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toolsettings", "0001_squashed_0003_auto_20180708_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="htmlsetting",
            name="value",
            field=models.TextField(blank=True, default="", verbose_name="HTML"),
        ),
        migrations.AlterField(
            model_name="htmlsetting",
            name="value_de",
            field=models.TextField(blank=True, default="", null=True, verbose_name="HTML"),
        ),
        migrations.AlterField(
            model_name="htmlsetting",
            name="value_en",
            field=models.TextField(blank=True, default="", null=True, verbose_name="HTML"),
        ),
    ]
