# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('inventory', 'barcode')]),
        ),
    ]
