# Generated by Django 2.2.12 on 2020-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Helpers can specify this prerequisite at registration'),
        ),
    ]
