# Generated by Django 2.2.11 on 2020-03-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_job_prerequisites'),
        ('prerequisites', '0002_prerequisite_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('event', 'name')},
        ),
        migrations.CreateModel(
            name='FulfilledPrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_prerequisite', models.BooleanField(default=False, verbose_name='Helper fulfils this prerequisite')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Helper')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prerequisites.Prerequisite')),
            ],
        ),
    ]
