# Generated by Django 5.2.9 on 2026-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prerequisites", "0002_auto_20210523_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prerequisite",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="prerequisite",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="prerequisite",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
