# Generated by Django 2.2.11 on 2020-03-21 22:36

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    replaces = [('prerequisites', '0004_auto_20200315_1110_squashed_0006_remove_prerequisite_helper_can_set'), ('prerequisites', '0005_auto_20200321_2334')]

    dependencies = [
        ('prerequisites', '0003_auto_20200314_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='description_de',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='description_en',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='name',
            field=models.CharField(help_text="The prerequisite's name in all internal views", max_length=200, verbose_name='Name'),
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='helper_can_set',
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
