# Generated by Django 2.2.11 on 2020-03-15 10:10

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0003_auto_20200314_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='description_de',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='description_en',
            field=django_bleach.models.BleachField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='long_name',
            field=models.CharField(default='test', help_text='Name displayed for helpers at registration', max_length=200, verbose_name='Registration name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='long_name_de',
            field=models.CharField(help_text='Name displayed for helpers at registration', max_length=200, null=True, verbose_name='Registration name'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='long_name_en',
            field=models.CharField(help_text='Name displayed for helpers at registration', max_length=200, null=True, verbose_name='Registration name'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='name',
            field=models.CharField(help_text="The prerequisite's name in all internal views", max_length=200, verbose_name='Name'),
        ),
    ]
