# Generated by Django 2.2.11 on 2020-03-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_auto_20200315_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together=set(),
        ),
    ]
