# Generated by Django 2.2.11 on 2020-03-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_auto_20200315_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='long_name_de',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='long_name_en',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_de',
            field=models.CharField(help_text="The prerequisite's name in all internal views", max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='name_en',
            field=models.CharField(help_text="The prerequisite's name in all internal views", max_length=200, null=True, verbose_name='Name'),
        ),
    ]
