# Generated by Django 2.2.11 on 2020-03-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0005_auto_20200321_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='helper_can_set',
        ),
    ]
