# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20160704_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inventory',
            field=models.BooleanField(default=False, verbose_name='Use the inventory functionality'),
        ),
    ]
