# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 14:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20170209_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shirt_sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UNKNOWN', 'Unknown'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('S_GIRLY', 'S (girly)'), ('M_GIRLY', 'M (girly)'), ('L_GIRLY', 'L (girly)'), ('XL_GIRLY', 'XL (girly)')], default=['UNKNOWN', 'S', 'M', 'L', 'XL', 'XXL', 'S_GIRLY', 'M_GIRLY', 'L_GIRLY', 'XL_GIRLY'], max_length=53, verbose_name='Available T-shirt sizes'),
        ),
    ]
