# Generated by Django 2.2.12 on 2020-06-13 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toollog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0043_auto_20200409_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelfertoolLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=16)),
                ('message', models.CharField(max_length=512)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('app', models.CharField(max_length=128)),
                ('extra', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Event')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Helper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(toollog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
