# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.EmailField(max_length=254, verbose_name="Name")),
            ],
        ),
    ]
