# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0002_auto_20160514_2307"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="includedgift",
            unique_together=set([("gift_set", "gift")]),
        ),
    ]
