# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0005_auto_20160611_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="deservedgiftset",
            name="present",
            field=models.BooleanField(default=False, verbose_name="Present"),
        ),
    ]
