# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0017_auto_20170210_1726"),
        ("gifts", "0007_helpersgifts_buy_shirt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deservedgiftset",
            name="present",
        ),
        migrations.AddField(
            model_name="helpersgifts",
            name="accomplished_shifts",
            field=models.ManyToManyField(blank=True, to="registration.Shift"),
        ),
    ]
