# Generated by Django 2.2.10 on 2020-03-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_add_field_helper_shifts'),
        ('gifts', '0009_remove_helpersgifts_accomplished_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_automatic_availability', models.BooleanField(default=False, verbose_name='Enable automatic availability confirmation at the end of a shift if absence was not reported')),
                ('default_deposit', models.IntegerField(blank=True, default=None, null=True, verbose_name='Default Deposit for a helper shift')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Event')),
            ],
        ),
    ]
