# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2016, 3, 5, 18, 4, 27, 134060, tzinfo=datetime.timezone.utc),
                help_text="First day of event",
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
    ]
