# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models.event


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160323_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(default=registration.models.event._default_mail, help_text='Used as sender of e-mails.', max_length=254, verbose_name='E-Mail'),
        ),
    ]
