# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_helper_privacy_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helper",
            name="privacy_statement",
            field=models.BooleanField(default=False, verbose_name="I agree with the following data privacy statement."),
        ),
    ]
