# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_event_changes_until"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="helper",
            options={"ordering": ["event", "surname", "firstname"]},
        ),
    ]
