# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0021_auto_20170509_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="hidden",
            field=models.BooleanField(
                default=False, verbose_name="If the job is publicly visible, the shift is not displayed."
            ),
        ),
    ]
