# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_shift_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='The shift is blocked and displayed as full.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='The shift is not visible.'),
        ),
    ]
