# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0023_auto_20170618_1101"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duplicate",
            fields=[
                ("deleted", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("existing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="registration.Helper")),
            ],
        ),
    ]
