# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0027_auto_20181020_2245"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["order", "pk"]},
        ),
        migrations.AddField(
            model_name="job",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order, highest number on top"),
        ),
    ]
