# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20190202_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-order', 'pk']},
        ),
    ]
