# Generated by Django 2.2.3 on 2019-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_helper_mail_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_phone',
            field=models.BooleanField(default=True, verbose_name='Ask for phone number'),
        ),
    ]
