# Generated by Django 2.2.11 on 2020-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0001_initial'),
        ('registration', '0031_event_ask_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='prerequisites.Prerequisite', verbose_name='Prerequisites for this job'),
        ),
    ]
