# Generated by Django 2.2.10 on 2020-03-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_event_ask_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, help_text='Helper was at shift', verbose_name='Present')),
                ('manual_presence', models.BooleanField(default=False, editable=False, help_text='presence was manually set')),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Helper')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Shift')),
            ],
            options={
                'unique_together': {('helper', 'shift')},
            },
        ),
    ]
