# Generated by Django 2.2.10 on 2020-03-11 18:21

from django.db import migrations


def migrate_attended_shift(apps, schema_editor):
    try:
        helpersgifts = apps.get_model('gifts', 'HelpersGifts')
    except LookupError:
        print("Nothing to migrate")
        # nothing has to be done if the helpersGift cannot be found!
        return

    HelperShifts = apps.get_model('registration', 'HelperShift')
    # set "present=True" if accomplished_shifts exists
    #     accomplished_shifts = models.ManyToManyField(
    #         'registration.Shift',
    #         blank=True,
    #     )

    for gifts in helpersgifts.objects.all():
        for shift in gifts.accomplished_shifts.all():
            HelperShifts(helper=gifts.helper,
                         shift=shift,
                         present=True).save()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_add_manual_helpershift'),
    ]

    operations = [
        migrations.RunPython(migrate_attended_shift),
    ]
