# Generated by Django 2.2.11 on 2020-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0003_auto_20200314_1817'),
        ('registration', '0032_job_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='prerequisites',
            field=models.ManyToManyField(through='prerequisites.FulfilledPrerequisite', to='prerequisites.Prerequisite'),
        ),
    ]
