# Generated by Django 2.2.11 on 2020-03-23 21:17

from django.db import migrations


def create_helpershift_relations(apps, schema_editor):
    Helper = apps.get_model("registration", "Helper")
    HelperShift = apps.get_model("registration", "HelperShift")
    HelpersGifts = apps.get_model("gifts", "HelpersGifts")

    for helper in Helper.objects.all():
        helpersgift = HelpersGifts.objects.filter(helper=helper)

        for shift in helper.shifts.all():
            helpershift = HelperShift(
                helper=helper,
                shift=shift,
            )

            if helpersgift.exists() and helpersgift[0].accomplished_shifts.filter(pk=shift.pk).exists():
                helpershift.present = True
                helpershift.manual_presence = True

            helpershift.save()

            # set timestamp separate as it has auto_now_add set
            helpershift.timestamp = helper.timestamp
            helpershift.save()


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0033_add_helpershift"),
        ("gifts", "0008_auto_20170401_1512"),
    ]

    operations = [
        migrations.RunPython(create_helpershift_relations, reverse_code=migrations.RunPython.noop),
    ]
