# Generated by Django 2.2.11 on 2020-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_helper_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prerequisites',
            field=models.BooleanField(default=False, verbose_name='Manage prerequisites for helpers'),
        ),
    ]
