# Generated by Django 2.2.10 on 2020-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_migrate_shiftattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='shifts',
        ),
    ]
