# Generated by Django 2.2.10 on 2020-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_remove_autogenerated_helpershifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='shifts',
            field=models.ManyToManyField(through='registration.HelperShift', to='registration.Shift'),
        ),
    ]
