# Generated by Django 2.2.11 on 2020-03-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_event_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='prerequisites.FulfilledPrerequisite', to='prerequisites.Prerequisite'),
        ),
    ]
