# Generated by Django 2.2.11 on 2020-03-23 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0034_fill_helpershift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helper",
            name="shifts",
        ),
    ]
