# Generated by Django 2.2.11 on 2020-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_event_ask_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='internal_comment',
            field=models.TextField(blank=True, verbose_name='Internal comment'),
        ),
    ]
