# Generated by Django 2.2.11 on 2020-03-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_event_prerequisites'),
        ('registration', '0035_add_field_helper_shifts'),
    ]

    operations = [
    ]
