# Generated by Django 2.2.11 on 2020-03-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_remove_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='shifts',
            field=models.ManyToManyField(through='registration.HelperShift', to='registration.Shift'),
        ),
    ]
