# Generated by Django 2.2.11 on 2020-03-23 21:17

from django.db import migrations


def create_helpershift_relations(apps, schema_editor):
    Helper = apps.get_model('registration', 'Helper')
    HelperShift = apps.get_model('registration', 'HelperShift')
    for helper in Helper.objects.all():
        for shift in helper.shifts.all():
            helpershift = HelperShift(
                helper=helper,
                shift=shift,
            )
            helpershift.save()

            # set timestamp separate as it has auto_now_add set
            helpershift.timestamp=helper.timestamp
            helpershift.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20200323_2217'),
    ]

    operations = [
        migrations.RunPython(create_helpershift_relations, reverse_code=migrations.RunPython.noop),
    ]
