# Generated by Django 2.2.11 on 2020-04-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_add_helpershift_to_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpershift',
            name='manual_presence',
            field=models.BooleanField(default=False, editable=False, verbose_name='Presence was manually set'),
        ),
    ]
