# Generated by Django 2.2.11 on 2020-03-14 12:26

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Event = apps.get_model("registration", "Event")
    EventAdminRoles = apps.get_model("registration", "EventAdminRoles")

    for event in Event.objects.all():
        for admin in event.admins.all():
            EventAdminRoles(
                event=event,
                user=admin,
                roles=[
                    "ADMIN",
                ],
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0038_eventadminroles"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
