# Generated by Django 2.2.11 on 2020-03-23 21:27

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_auto_20200323_2227'),
    ]

    operations = [
        # This just does nothing on sqlite
        # If you are not a superuser, this migration will fail. so please execute on the database

        # CREATE EXTENSION pg_trgm;

        # and remove the next line

        TrigramExtension(),
    ]
