# Generated by Django 2.2.11 on 2020-03-14 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0041_add_new_admins"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventadminroles",
            unique_together={("event", "user")},
        ),
    ]
