# Generated by Django 3.2.6 on 2021-08-06 11:35

from django.db import migrations


def migrate_vegetarian(apps, schema_editor):
    Helper = apps.get_model("registration", "Helper")

    for helper in Helper.objects.all():
        if helper.vegetarian:
            helper.nutrition = "VEGETARIAN"
            helper.save()


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0049_auto_20210806_1249"),
    ]

    operations = [
        migrations.RunPython(migrate_vegetarian, reverse_code=migrations.RunPython.noop),
    ]
