# Generated by Django 3.2.6 on 2021-08-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0050_migrate_vegetarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='vegetarian',
        ),
    ]
