# Generated by Django 3.2.6 on 2021-08-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_remove_helper_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ask_nutrition',
            field=models.BooleanField(default=True, verbose_name='Ask for preferred nutrition'),
        ),
    ]
