# Generated by Django 3.2.13 on 2022-05-29 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0057_auto_20220528_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="helper",
            name="validation_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
