# Generated by Django 3.2.14 on 2022-07-09 17:31

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0061_remove_old_job_job_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="important_notes",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                verbose_name="Important notes",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="important_notes_de",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                null=True,
                verbose_name="Important notes",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="important_notes_en",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                null=True,
                verbose_name="Important notes",
            ),
        ),
    ]
