# Generated by Django 3.2.16 on 2022-12-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0062_auto_20220709_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pretix",
            field=models.BooleanField(default=False, verbose_name="Create tickets in Pretix"),
        ),
    ]
