# Generated by Django 4.1.2 on 2022-10-15 17:01

from django.conf import settings
from django.db import migrations, models
import registration.models.event


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0063_alter_event_url_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url_name",
            field=models.SlugField(
                help_text="May contain letters, numbers, underscores or hyphens.",
                max_length=200,
                unique=True,
                validators=[registration.models.event._validate_url_blocklist],
                verbose_name="Name for URL",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_admins",
            field=models.ManyToManyField(
                blank=True, related_name="+", through="registration.JobAdminRoles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
