# Generated by Django 3.2.16 on 2023-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_helper_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
