# Generated by Django 4.2.19 on 2025-02-15 18:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0064_alter_event_url_name_alter_job_job_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="shirt_sizes",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("NO", "I do not want a T-Shirt"),
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("3XL", "3XL"),
                    ("4XL", "4XL"),
                    ("XXS_GIRLY", "XXS (girly)"),
                    ("XS_GIRLY", "XS (girly)"),
                    ("S_GIRLY", "S (girly)"),
                    ("M_GIRLY", "M (girly)"),
                    ("L_GIRLY", "L (girly)"),
                    ("XL_GIRLY", "XL (girly)"),
                    ("XXL_GIRLY", "XXL (girly)"),
                    ("3XL_GIRLY", "3XL (girly)"),
                    ("4XL_GIRLY", "4XL (girly)"),
                ],
                default=("S", "M", "L", "XL", "XXL", "S_GIRLY", "M_GIRLY", "L_GIRLY", "XL_GIRLY"),
                max_length=250,
                verbose_name="Available T-shirt sizes",
            ),
        ),
        migrations.AlterField(
            model_name="helper",
            name="shirt",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("NO", "I do not want a T-Shirt"),
                    ("XXS", "XXS"),
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                    ("3XL", "3XL"),
                    ("4XL", "4XL"),
                    ("XXS_GIRLY", "XXS (girly)"),
                    ("XS_GIRLY", "XS (girly)"),
                    ("S_GIRLY", "S (girly)"),
                    ("M_GIRLY", "M (girly)"),
                    ("L_GIRLY", "L (girly)"),
                    ("XL_GIRLY", "XL (girly)"),
                    ("XXL_GIRLY", "XXL (girly)"),
                    ("3XL_GIRLY", "3XL (girly)"),
                    ("4XL_GIRLY", "4XL (girly)"),
                ],
                default="UNKNOWN",
                max_length=20,
                verbose_name="T-shirt",
            ),
        ),
    ]
