# Generated by Django 4.1.8 on 2023-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0064_alter_event_url_name_alter_job_job_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="collect_nutritional_preferences",
            field=models.BooleanField(default=True, verbose_name="Collect helper nutritional preferences"),
        ),
    ]
