# Generated by Django 4.2 on 2023-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0064_alter_event_url_name_alter_job_job_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ask_nutrition",
            field=models.BooleanField(default=True, verbose_name="Ask for preferred nutrition for this job"),
        ),
    ]
