# Generated by Django 4.2 on 2023-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0065_job_ask_nutrition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helper",
            name="nutrition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_PREFERENCE", "No preference"),
                    ("VEGETARIAN", "Vegetarian"),
                    ("VEGAN", "Vegan"),
                    ("OTHER", "Other (please specify in comment)"),
                ],
                default="NO_PREFERENCE",
                help_text="This helps us estimating the food for our helpers.",
                max_length=20,
                verbose_name="Nutrition",
            ),
        ),
    ]
