# Generated by Django 4.2.27 on 2025-12-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0065_alter_event_shirt_sizes_alter_helper_shirt"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ask_mxid",
            field=models.BooleanField(default=True, verbose_name="Ask for Matrix ID"),
        ),
        migrations.AddField(
            model_name="helper",
            name="mxid",
            field=models.CharField(default="", max_length=200, verbose_name="Matrix ID"),
            preserve_default=False,
        ),
    ]
