# Generated by Django 5.2.9 on 2026-01-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0066_event_ask_mxid_helper_mxid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ask_mxid",
            field=models.BooleanField(default=False, verbose_name="Ask for Matrix ID"),
        ),
        migrations.AlterField(
            model_name="event",
            name="ask_nutrition",
            field=models.BooleanField(default=False, verbose_name="Ask for preferred nutrition"),
        ),
        migrations.AlterField(
            model_name="event",
            name="ask_phone",
            field=models.BooleanField(default=False, verbose_name="Ask for phone number"),
        ),
        migrations.AlterField(
            model_name="event",
            name="ask_shirt",
            field=models.BooleanField(default=False, verbose_name="Ask for T-shirt size"),
        ),
    ]
