# Generated by Django 5.2.9 on 2026-01-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0067_alter_event_ask_mxid_alter_event_ask_nutrition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="important_notes",
            field=models.TextField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                verbose_name="Important notes",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="important_notes_de",
            field=models.TextField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                null=True,
                verbose_name="Important notes",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="important_notes_en",
            field=models.TextField(
                blank=True,
                help_text="This text is directly shown on the registration page, so that helpers cannot miss notes in the description.",
                null=True,
                verbose_name="Important notes",
            ),
        ),
    ]
