# Generated by Django 5.2.9 on 2026-01-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0068_alter_job_description_alter_job_description_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="imprint",
            field=models.TextField(
                blank=True, help_text="Displayed at the bottom of all pages for the event.", verbose_name="Contact"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="imprint_de",
            field=models.TextField(
                blank=True,
                help_text="Displayed at the bottom of all pages for the event.",
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="imprint_en",
            field=models.TextField(
                blank=True,
                help_text="Displayed at the bottom of all pages for the event.",
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered",
            field=models.TextField(
                blank=True, help_text="Displayed after registration.", verbose_name="Text after registration"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_de",
            field=models.TextField(
                blank=True, help_text="Displayed after registration.", null=True, verbose_name="Text after registration"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registered_en",
            field=models.TextField(
                blank=True, help_text="Displayed after registration.", null=True, verbose_name="Text after registration"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="Displayed as first text of the registration form.",
                verbose_name="Text before registration",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="text_de",
            field=models.TextField(
                blank=True,
                help_text="Displayed as first text of the registration form.",
                null=True,
                verbose_name="Text before registration",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="text_en",
            field=models.TextField(
                blank=True,
                help_text="Displayed as first text of the registration form.",
                null=True,
                verbose_name="Text before registration",
            ),
        ),
    ]
