# Generated by Django 5.2.9 on 2026-01-13 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0069_alter_event_imprint_alter_event_imprint_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="corona",
        ),
    ]
