# Generated by Django 5.2.9 on 2026-01-13 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0070_remove_event_corona"),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "corona_contacttracingdata"',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "corona_coronasettings"',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
