# Show this announcement on every page (for example for maintenance)
#announcement: ""

# Location of uploaded files, static files and temporary files.
# Relative paths are relative to the git directory, absolute paths
# are also possible.
files:
    static: "static"
    media: "media"
    tmp: "/tmp"

# Language settings
# Possible values: de, en
language:
    # Default language if not specified by the browser
    default: "de"

    # Language used for badges
    badges: "de"

    # Timezone
    timezone: "Europe/Berlin"

    # Default country for Corona contact tracing (ISO-3166-1)
    country: "DE"

# Database connection
database:
    # SQLite
    backend: "sqlite3"
    name: "db.sqlite3"

    # MySQL
    #backend: "mysql"
    #name: "helfertool"
    #user: "helfertool"
    #password: "<PASSWORD>"
    #host: 127.0.0.1
    #port: 3306

    # PostgreSQL
    #backend: "postgresql"
    #name: "helfertool"
    #user: "helfertool"
    #password: "<PASSWORD>"
    #host: 127.0.0.1
    #port: 5432

    # Additional options like an init_command
    # Refer to the Django documentation for further options
    #options:
    #    init_command: "SET sql_mode='STRICT_TRANS_TABLES';"

# RabbitMQ connection
rabbitmq:
    # Name of the vHost
    vhost: ""

    # Login credentials
    user: "guest"
    password: "guest"

    # Hostname and port
    host: 127.0.0.1
    port: 5672

# Mail server and settings
mail:
    # Connection to mail server for sending
    send:
        host: "localhost"
        port: 25
        user: null
        password: null
        tls: false
        starttls: false

    # Connection to mail server for receiving
    #receive:
    #    host: "localhost"
    #    port: 993
    #    user: "helfertool"
    #    password: "<PASSWORD>"
    #    tls: true
    #    starttls: false
    #
    #    # The IMAP folder that should be checked for new mails
    #    folder: "INBOX"
    #
    #    # Time between checks (in seconds)
    #    interval: 300

    # Sender address and display name for all outgoing mails
    sender_address: "helfertool@localhost"
    sender_name: "Helfertool"

    # Forward received mails that are not handled automatically to this address (with this display name)
    #forward_unhandled_address: "helfertoolintern@localhost"
    #forward_unhandled_name: "Helfertool"

    # Batch size if a high amount of mails is sent
    # This is currently only used for the newsletter, the other mails are sent
    # with all addresses in BCC!
    batch_size: 200
    batch_gap: 5

# Authentication settings
# Note: It is recommended to only enabled LDAP or OpenID Connect, not both at the same time.
authentication:
    # Get users from LDAP
    #ldap:
    #    # Connection details
    #    server:
    #        host: "ldaps://ldap.helfertool.org"
    #        bind_dn: "cn=helfertool,ou=Roles,dc=helfertool,dc=org"
    #        bind_password: null
    #
    #    # LDAP schema and attributes
    #    schema:
    #        # User definition
    #        user_dn_template: "uid=%(user)s,ou=People,dc=helfertool,dc=org"
    #        first_name_attr: "givenName"
    #        last_name_attr: "sn"
    #        email_attr: "mail"
    #
    #        # Group definition
    #        # See https://django-auth-ldap.readthedocs.io/en/latest/groups.html?highlight=AUTH_LDAP_GROUP_TYPE#types-of-groups
    #        # for a list of all posible values for group_type
    #        group_type: "GroupOfNamesType"
    #        group_base_dn: "ou=Groups,dc=helfertool,dc=org"
    #        group_object_class: "groupOfNames"
    #
    #    # Permissions based on groups
    #    groups:
    #        login: null
    #        admin: "cn=admins,ou=Group,dc=helfertool,dc=org"


    ## Get users over OpenID Connect
    #oidc:
    #    # Name of the provider (only for login view)
    #    provider_name: "OpenID Connect"
    #
    #    # Provider details
    #    provider:
    #        # Endpoint URLs
    #        authorization_endpoint: "https://auth.helfertool.org/auth/realms/test/protocol/openid-connect/auth"
    #        token_endpoint: "https://auth.helfertool.org/auth/realms/test/protocol/openid-connect/token"
    #
    #        # Optional: If present, the endpoint is must return all relevant info for authentication and authorization.
    #        #           If omitted, information is expected to be contained in the id_token
    #        user_endpoint: "https://auth.helfertool.org/auth/realms/test/protocol/openid-connect/userinfo"
    #
    #        # URI to get JWKS
    #        jwks_uri: "https://auth.helfertool.org/auth/realms/test/protocol/openid-connect/certs"
    #
    #        # Client ID and secret
    #        client_id: "helfertool"
    #        client_secret: "<SECRET>"
    #
    #        # Controls the session cookie SameSite attribute, forcing it to "Lax". This is necessary if your OIDC provider
    #        # resides on a different top level domain name than the Helfertool (error message: "Login failed")
    #        # Set it to true in this case.
    #        thirdparty_domain: false
    #
    #        # It could happen that the user is disabled or claims change. So we can redirect the users from time to time
    #        # to the OIDC provider and validate if they are still allowed to login.
    #        # Time in minutes, set to 0 to disable it (Note: the idle timeout of the provider should be higher than this value)
    #        renew_check_interval: 15
    #
    #        # If the session is only terminated in the application, the login via OIDC works again without asking for credentials.
    #        # Therefore, we can also trigger a logout at the OIDC provider.
    #        # The URL is less well specified and depends on the provider (here: Keycloak)
    #        logout:
    #            endpoint: "https://auth.helfertool.org/auth/realms/test/protocol/openid-connect/logout"
    #            redirect_parameter: "redirect_uri"
    #
    #    # Permissions based on claims
    #    claims:
    #        # There are two types to handle claims
    #        # 1) direct: the claim is directly compared
    #        # 2) member: the claim is a list and it is checked if the specified value is included (useful for groups/roles)
    #        # The path is a JMESPath. Plain claim names like "roles" are also a valid JMESPath.
    #        login:
    #            #compare: "direct"
    #            #path: "helfertool_login"
    #            #value: true
    #            compare: "member"
    #            path: "roles"
    #            value: "helfertool_login"
    #
    #        admin:
    #            #compare: "direct"
    #            #path: "helfertool_admin"
    #            #value: true
    #            compare: "member"
    #            path: "roles"
    #            value: "helfertool_admin"

    # Prepend character to all locally created users
    # This is useful if you have for example users from LDAP but also local
    # users. The additional character like '@' is used to prevent identical
    # user names for different users
    local_user_char: null

# Logging and alerting
logging:
    # Sent mails on internal server errors
    mails:
        - root@localhost

    # Syslog logging
    #syslog:
    #    # Log level that will be sent to syslog: INFO, WARNING, ERROR
    #    level: 'INFO'
    #
    #    # Server, port and protocol
    #    # UDP is recommended. With TCP, the syslog server needs to run and accept connections when the Helfertool is started.
    #    server: 'localhost'
    #    port: 514
    #    protocol: 'udp'
    #
    #    # Syslog facility to use
    #    facility: 'local7'

    # Store all event-related events in the database.
    # The log entries are only stored as long as the event exists and are deleted with the event.
    #database: true

# Security settings
security:
    # Do not activate debugging in productive environments!
    debug: true

    # Unique and secret key
    secret: "change_this_for_production"

    # URLs that are used for the software
    allowed_hosts:
    #    - "app.helfertool.org"
    #    - "www.app.helfertool.org"

    # Application is behind additional/second proxy. In this case, the HTTP
    # header X-Forwarded-Host is used. Example: Apache > nginx > uwsgi
    behind_proxy: False

    # Account lockout
    lockout:
        # Number of failed login attempts until lockout
        limit: 5

        # Lockout duration in minutes
        time: 10

    # Minimal password length (for local accounts)
    password_length: 12

# Helfertool features can be disabled globally here (true means enabled, false means disabled).
# If a flag is changed to disabled, all events are modified automatically after a reload (of celery).
# Enabling a feature does not change event settings.
features:
    # Collect mail addresses for newsletter.
    # This also disables the unsubscribe link. If the feature was used previously and is now disabled,
    # you should take care of the stored data (greetings from GDPR)
    newsletter: true

    # Further features
    badges: true
    gifts: true
    prerequisites: true
    inventory: true
    corona: true

# Custom URLs, mail addresses, ...
customization:
    # Title for all pages
    title: "Helfertool"

    # Modify certain properties for the general helfertool to display
    display:
        # Maximum years of events to be displayed by default on the main page
        events_last_years: 2

    # Fuzzy search for helper names
    # Only available on PostgrSQL with pg_trgm extension, disabled automatically otherwise
    search:
        # Values between 0.2 (show more results) and 0.5 (show less results) seem to be reasonable.
        # The similarity threshold of 0.3 was selected based on a name database of ~4000 western
        # european names and the gut feel when a good match was actually found.
        similarity: 0.3

        # If PostgreSQL is used and pg_trgm is installed, the similarity search is automatically used.
        # If you do not want to have this, disable it here.
        disable_similarity: false

    # There are some external links that should/can be changed
    urls:
        # Imprint with contact details
        imprint: "https://app.helfertool.org/impressum/"

        # Privacy statement
        privacy: "https://app.helfertool.org/datenschutz/"

        # Link to documentation (usually no change necessary)
        docs: "https://docs.helfertool.org"

    # Contact address for support requests
    contact_address: "helfertool@localhost"

# Badge settings
badges:
    # Path to pdflatex binary
    pdflatex: "/usr/bin/pdflatex"

    # Alternative default template, path to tex file
    # Relative paths again are relative to the git directory
    template: "src/badges/latextemplate/badge.tex"

    # Maximum photo size in kb
    photo_max_size: 1000

    # Maximum number of copies for special badges
    special_badges_max: 50

    # Time until PDF file is deleted after it was created in minutes
    pdf_timeout: 30

    # Time until files are really deleted after cleanup was triggered
    # in minutes
    rm_delay: 2

# Newsletter settings
newsletter:
    # Newsletter subscriptions need to be confirmed with by clicking on a link.
    # This setting specifies how long the link is valid (days). Afterwards, the mail address is deleted.
    subscribe_deadline: 3
