# Generated by Django 3.2.16 on 2022-12-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registration", "0063_event_pretix"),
    ]

    operations = [
        migrations.CreateModel(
            name="PretixSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registration.event")),
            ],
        ),
        migrations.CreateModel(
            name="PretixOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("failed", models.BooleanField(default=False, verbose_name="Order failed")),
                ("pretix_item_ref", models.CharField(max_length=100, verbose_name="Reference to the Pretix item")),
                ("pretix_order_id", models.CharField(max_length=20, null=True, verbose_name="Id of the Pretix order")),
                (
                    "pretix_order_position_id",
                    models.IntegerField(null=True, verbose_name="Id of the position of the item in the Pretix order"),
                ),
                (
                    "pretix_order_link",
                    models.CharField(max_length=200, null=True, verbose_name="Public link to the Pretix order"),
                ),
                (
                    "pretix_ticket_code",
                    models.CharField(max_length=200, null=True, verbose_name="Code printed on the Pretix ticket"),
                ),
                (
                    "helper",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="registration.helper"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PretixItemJobLinkage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pretix_item_ref", models.CharField(max_length=100, verbose_name="Reference to the Pretix item")),
                ("job", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="registration.job")),
            ],
        ),
    ]
