# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 13:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0003_badgedesign_bg_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgedesign",
            name="bg_color",
            field=models.CharField(
                default="#FFFFFF",
                help_text="E.g. #00ff00",
                max_length=7,
                validators=[django.core.validators.RegexValidator("^#[a-fA-F0-9]{6}$")],
                verbose_name="Background color",
            ),
        ),
    ]
