# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0007_badgesettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgesettings",
            name="only_coordinators",
            field=models.BooleanField(default=False, verbose_name="Badges only for coordinators"),
        ),
    ]
