# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_auto_20170414_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Barcode'),
        ),
    ]
