# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:06
from __future__ import unicode_literals

from django.db import migrations


def copy_barcode(apps, schema_editor):
    Badge = apps.get_model("badges", "Badge")
    for row in Badge.objects.all():
        row.barcode = row.pk
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0010_badge_barcode"),
    ]

    operations = [
        migrations.RunPython(copy_barcode, reverse_code=migrations.RunPython.noop),
    ]
