# Generated by Django 3.1.1 on 2020-09-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20200409_1711'),
        ('badges', '0016_badge_fill_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.event'),
        ),
    ]
